// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDHSQKlGjjvnS7Dei24VV9lhjDK9D2RDB8',
    appId: '1:735012231770:web:5e907416d5d16ae8885663',
    messagingSenderId: '735012231770',
    projectId: 'matjarifirebase001',
    authDomain: 'matjarifirebase001.firebaseapp.com',
    storageBucket: 'matjarifirebase001.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDhzQe2Wtj5GjWBOsICu6UbTrh0l9qL_CE',
    appId: '1:735012231770:android:c6f22e76e3c609b3885663',
    messagingSenderId: '735012231770',
    projectId: 'matjarifirebase001',
    storageBucket: 'matjarifirebase001.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDGFz4dylL5yeYbknJdPkL3_eUtSiUEeHU',
    appId: '1:735012231770:ios:f62f112dd875f7ef885663',
    messagingSenderId: '735012231770',
    projectId: 'matjarifirebase001',
    storageBucket: 'matjarifirebase001.firebasestorage.app',
    iosBundleId: 'com.matjari.matjari',
  );
}
